### PR TITLE
bump github action versions

### PR DESCRIPTION
**Pull request by elisalle**

### CODE REVIEW

**Review by margrietpalm — CHANGES_REQUESTED** [review]
This modifies the release workflow, but that is skipped in de CI. I would really like to see a succesfull release with these changes.

**Comment by elisalle** [comment]
> This modifies the release workflow, but that is skipped in de CI. I would really like to see a succesfull release with these changes.

how would you like me to test that before merging the PR?

**Comment by margrietpalm** [comment]
> > This modifies the release workflow, but that is skipped in de CI. I would really like to see a succesfull release with these changes.
> 
> how would you like me to test that before merging the PR?

Create a tag with that results in a package with a name that pip doesn't automatically installs

**Comment by elisalle** [comment]
tested and it works

**Review by margrietpalm — APPROVED** [review]
Great!

**Pull request merged**
